---
# Based on the instructions at http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-agent-install.html

- name: Create directory for for ECS agent
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  loop:
    - /var/log/ecs
    - /etc/ecs
    - /var/lib/ecs/data

- name: Create directory for for ECS agent
  become: true
  ansible.builtin.file:
    path: /etc/ecs/ecs.config
    state: touch
    mode: '0755'

- name: Populate Apt's Cache with package definitions to avoid "no such package" errors
  ansible.builtin.apt:
    update_cache: true

- name: install pip
  become: true
  apt: 
    name: python-pip 
    state: present 

- name: install pip3
  become: true
  apt: 
    name: python3-pip 
    state: present 

- name: Make sure vital python packages are installed beforehand
  become: true
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
      - docker

- name: Set route_localnet
  sysctl:
    name: net.ipv4.conf.all.route_localnet
    value: 1
    sysctl_set: yes

- name: Setup port forwarding from 80 to 51679 for metadata (1)
  iptables:
    table: nat
    chain: PREROUTING
    protocol: tcp
    destination: 169.254.170.2
    destination_port: 80
    jump: DNAT
    to_destination: 127.0.0.1:51679
    #to_ports: 51679

- name: Setup port forwarding from 80 to 51679 for metadata (2)
  iptables:
    table: nat
    chain: OUTPUT
    destination: 169.254.170.2
    protocol: tcp
    match: tcp
    destination_port: 80
    jump: REDIRECT
    to_ports: 51679

- name: create ecs environment file
  template:
    src=ecs.j2
    dest=/etc/default/ecs
    owner=root
    group=root
    mode=0644

# Option 1: Use systemd to start ECS agent container
# https://docs.aws.amazon.com/AmazonECS/latest/developerguide/example_user_data_scripts.html

# - name: create systemd docker service for ecs-agent
#   template:
#     src=docker-container@ecs-agent.service.j2
#     dest=/etc/systemd/system/docker-container@ecs-agent.service
#     owner=root
#     group=root
#     mode=0644
#   when: ubuntu_ecs_agent_start_mode == "systemd"

# - name: enable ecs-agent systemd service
#   systemd:
#     name: docker-container@ecs-agent
#     enabled: yes
#   when: ubuntu_ecs_agent_start_mode == "systemd"

# https://docs.aws.amazon.com/batch/latest/userguide/create-batch-ami.html
# - name: Remove the persistent data checkpoint file from ecs-agent
#   file:
#     state: absent
#     path: "/var/lib/ecs/data/ecs_agent_data.json"

# Option 2: manage ECS agent container with Docker natively
- name: Configure and run the ecs-agent container
  docker_container:
    name: ecs-agent
    image: amazon/amazon-ecs-agent:latest
    state: started
    restart_policy: always
    detach: true
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/ecs/:/log
      - /var/lib/ecs/data:/data
    env_file: /etc/ecs/ecs.config
    env:
        ECS_LOGFILE: /log/ecs-agent.log
        ECS_DATADIR: /data/
        ECS_ENABLE_TASK_IAM_ROLE: "true"
        ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST: "true"
    privileged: yes 
  when: ubuntu_ecs_agent_start_mode == "docker"