---
# Supported annotations
# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/
apiVersion: v1
kind: Service
metadata:
  name: toureast-gameplay-prd-svc
  namespace: xct-apps
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
  selector:
    app: toureast-gameplay-prd
