apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-agent-config
  namespace: default
data:
  config.hcl: |
    auto_auth {
      method "kubernetes" {
        mount_path = "auth/kubernetes"
        config = {
          role = "xct-apps"
        }
      }

      sink "file" {
        config = {
          path = "/vault/token"
        }
      }
    }

    vault {
      address = "https://vault.xctuality.com"
      tls_skip_verify = true
    }
