pipeline {
    agent any

    options {
        skipStagesAfterUnstable()
    }
    environment {
        HOME = '.'
        GITHUB_ORG = credentials("GITHUB_MAIN_ORG")
        GITHUB_PAT = credentials("GITHUB_PAT")
        GITHUB_REPO = "carnelian"
        GITHUB_BRANCH = "SIT"
        GITHUB_USER = "LivingLegacyDevTeam"
        SERVICE_PORT = 9001
        SIT_SERVER = '209.127.228.14'
        DOCKER_REGISTRY_URL = "https://registry-1.docker.io/v2/"
        DOCKER_REGISTRY_CREDS = credentials('DOCKER_REGISTRY')
        KUBECONFIG = credentials('kubeconfig-ts-staging')
    }

    stages {
        stage('Clone repository of Carnelian') { 
            steps { 
                script{
                    checkout scm
                    pwd
                }
            }
        }

        stage('Build Image') {
            steps { 
                sendBuildNotification('📣', '#439FE0', 'STARTED', env.JOB_NAME, env.BUILD_NUMBER, 'SIT', env.BUILD_URL)
                script{
                    app = docker.build("aslitechnologies/casino-test-app", "--build-arg GITHUB_ORG=$GITHUB_ORG --build-arg GITHUB_PAT=$GITHUB_PAT --build-arg GITHUB_REPO=$GITHUB_REPO --build-arg GITHUB_BRANCH=$GITHUB_BRANCH --build-arg GITHUB_USER=$GITHUB_USER --force-rm --no-cache -f $GITHUB_REPO/Dockerfile .")
                }
            }
        }

        stage('Test Image'){
            steps {
                 script{
                 sh "docker run -p $SERVICE_PORT:80 --name casino-test-app -d --rm aslitechnologies/casino-test-app"
                 sh 'sleep  2'
                 sh "nc -zv localhost $SERVICE_PORT"
                 sh 'docker stop casino-test-app'
                 }                   
            }
        }

        stage('Push Image to Registry') {
            steps {
                script{
                    docker.withRegistry("$DOCKER_REGISTRY_URL", "DOCKER_REGISTRY") {   
                        app.push("sit-build-${env.BUILD_NUMBER}")
                        sh 'docker rmi -f $(docker images -q aslitechnologies/casino-test-app)'
                    }
                }
            }
        }

        stage('K8s Deployment') {
            steps {
                script{
                    dir('carnelian/k8s') {
                        sh 'echo ${BUILD_NUMBER}'
                        sh 'sed -i s/BUILD/${BUILD_NUMBER}/g casino-test-development-app.yaml'
                        sh 'kubectl apply -f casino-test-development-app.yaml --kubeconfig=${KUBECONFIG}' // --validate=false
                    }
                }
            }
        }

    }

    post {
        success {
            script {
                sendBuildNotification('✅', '#36a64f', 'COMPLETED', env.JOB_NAME, env.BUILD_NUMBER, 'SIT', env.BUILD_URL)
            }
        }
        failure {
            script {
                sendBuildNotification('❌', '#ff0000', 'FAILED', env.JOB_NAME, env.BUILD_NUMBER, 'SIT', env.BUILD_URL)
            }
        }
        always {
            script {
                sh "docker system prune -f"
            }
        }
    }

}

def sendApprovalNotification(color, jobName, buildNumber, environment, buildUrl, tagged) {
    def message = "🚦 Build *APPROVAL*: Pipeline ${jobName} | \n *Job* # ${buildNumber} | *Environment*: ${environment} | More Info: ${buildUrl} \n 🗣️ ${tagged} "
    slackSend(channel: 'rsi-builds-approval', color: color, message: message)
}

def sendBuildNotification(emoji, color, status, jobName, buildNumber, environment, buildUrl) {
    def message = "${emoji} Build *${status.toUpperCase()}*: Pipeline ${jobName} | \n *Job* # ${buildNumber} | *Environment*: ${environment} | More Info: ${buildUrl}"
    slackSend(channel: 'rsi-tech-builds', color: color, message: message)
}