properties([
    parameters([
        choice(
            choices: ['vpc'],
            name: 'Module_Name'
        ), 
        choice(
            choices: [
                'plan',
                'apply',
                'destroy'],
            name: 'Terraform_Action'
        )]
    )
])
pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    environment {
        HOME = '.'
    }
    stages {

        stage('Terraform Notification') {
            steps { 
                sendBuildNotification('📣', '#439FE0', 'STARTED', env.JOB_NAME, env.BUILD_NUMBER, 'Cloud Infrastructure', env.BUILD_URL)
            }
        }
        
        stage('Terraform Init') { 
            steps { 
                echo "Enter File Name ${params.Module_Name}"
                withAWS(credentials: 'rsi-lower', region: 'ap-southeast-1') {
                    script{
                        sh 'terraform -chdir=provider/aws/tier/rsi-lower-env/${Module_Name}/ init'
                    }
                }
            }
        }

        stage('Terraform Action') {
            steps {
                echo "${params.Terraform_Action}"
                withAWS(credentials: 'rsi-lower', region: 'ap-southeast-1') {
                    // sh 'terraform get -update'
                    script {
                        if (params.Terraform_Action == 'plan') {
                            // sh 'terraform -chdir=provider/aws/tier/rsi-lower-env/${Module_Name}/ plan'
                        }   else if (params.Terraform_Action == 'apply') {
                            // sh 'terraform -chdir=provider/aws/tier/rsi-lower-env/${Module_Name}/ apply -auto-approve'
                        }   else if (params.Terraform_Action == 'destroy') {
                            sendApprovalNotification("#FFFF00", env.JOB_NAME, env.BUILD_NUMBER, 'Cloud Infrastructure', env.BUILD_URL, '<@U06JFNU0G1E> <@U06HCCN062K> <!subteam^S06N3FYNEN7>')
                            input("Do you really want to destroy it?")
                            // sh 'terraform -chdir=provider/aws/tier/rsi-lower-env/${Module_Name}/ destroy -auto-approve'
                        } else {
                            error "Invalid value for Terraform_Action: ${params.Terraform_Action}"
                        }
                    }
                }
            }
            post {
                failure {
                    script {
                        error "Approval denied, stopping the pipeline"
                    }
                }
            }
        }
    
    }

    post {
        success {
            script {
                sendBuildNotification('✅', '#36a64f', 'COMPLETED', env.JOB_NAME, env.BUILD_NUMBER, 'Cloud Infrastructure', env.BUILD_URL)
            }
        }
        failure {
            script {
                sendBuildNotification('❌', '#ff0000', 'FAILED', env.JOB_NAME, env.BUILD_NUMBER, 'Cloud Infrastructure', env.BUILD_URL)
            }
        }
        always {
            cleanWs()
        }
    }
}


def sendApprovalNotification(color, jobName, buildNumber, environment, buildUrl, tagged) {
    def message = "🚦 Build *APPROVAL*: Pipeline ${jobName} | *Job* # ${buildNumber} | *Service*: Amazon EKS | *Environment*: ${environment} | More Info: ${buildUrl} \n 🗣️ ${tagged} "
    // slackSend(channel: 'rsi-builds-approval', color: color, message: message)
    slackSend(color: color, message: message)
}

def sendBuildNotification(emoji, color, status, jobName, buildNumber, environment, buildUrl) {
    def message = "${emoji} Build *${status.toUpperCase()}*: Pipeline ${jobName} | *Job* # ${buildNumber} | *Service*: Amazon EKS | *Environment*: ${environment} | More Info: ${buildUrl}"
    // slackSend(channel: 'rsi-tech-builds', color: color, message: message)
    slackSend(color: color, message: message)
}