---
# tasks file for roles/append-value-to-file
- name: Insert variables in ecs.config 
  ansible.builtin.blockinfile:
    path: /etc/ecs/ecs.config
    append_newline: true
    prepend_newline: true
    block: |
      ECS_DATADIR=/data
      ECS_ENABLE_TASK_IAM_ROLE=true
      ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
      ECS_LOGFILE=/log/ecs-agent.log
      ECS_AVAILABLE_LOGGING_DRIVERS=["json-file","awslogs"]
      ECS_LOGLEVEL=info
      ECS_CLUSTER=DOS2WINCLUSTER
      ECS_ENABLE_AWSLOGS_EXECUTIONROLE_OVERRIDE=true