---
# Supported annotations
# https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.7/guide/service/annotations/
apiVersion: v1
kind: Service
metadata:
  name: toureast-teaser-prd-svc
  namespace: xctualyfe-apps
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: toureast-teaser-prd
