---
- name: Provisioning the server requirements
  hosts: all
  become: true
  roles:
  ## Execute build and deploy script
    - role: "~/Documents/personal/devops/infra-as-code/ansible/roles/jenkins"