---
- name: Provisioning the server requirements
  hosts: all
  become: true
  vars:
    apache_config_files:
      - "site.conf"
    docker_file:
      - "Dockerfile"      
  roles:
    ## Execute build and deploy script
    - role: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/ansible/roles/apache2"
      vars:
        SOURCE_PATH: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/terraform/provider/aws/environments/global-devsecops-env/ec2/jenkins/assets/apache2"
        FILENAME: "{{ apache_config_files }}"
    - role: /mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/ansible/roles/docker
    - role: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/ansible/roles/copy-local-to-remote"
      vars:
        SOURCE_PATH: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/terraform/provider/aws/environments/global-devsecops-env/ec2/jenkins/assets/scripts"
        FILENAME: "{{ docker_file }}"    
        REMOTE_DESTINATION_PATH: "."


