---
- name: Provisioning the server requirements
  hosts: all
  become: true
  vars:
    apache_config_files:
      - "site.conf"
    files:
      - "prometheus.yml" 
      - "blackbox.yml" 
  roles:
    ## Execute build and deploy script
    - role: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/ansible/roles/apache2"
      vars:
        SOURCE_PATH: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/terraform/provider/aws/environments/global-devsecops-env/ec2/monitoring/assets/apache2"
        FILENAME: "{{ apache_config_files }}"
    - role: /mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/ansible/roles/docker
    - role: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/ansible/roles/copy-local-to-remote"
      vars:
        SOURCE_PATH: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/terraform/provider/aws/environments/global-devsecops-env/ec2/monitoring/assets/scripts"
        FILENAME: "{{ files }}"    
        REMOTE_DESTINATION_PATH: "."
    - role: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/ansible/roles/execute-script"
      vars:
        SCRIPT: "/mnt/d/Users/RouVin/Documents/xctuality/devops/infra-as-code/terraform/provider/aws/environments/global-devsecops-env/ec2/monitoring/assets/scripts/monitoring-tool-container.sh"